FROM docker.io/alpine:3.22

RUN apk add --no-cache \
    font-dejavu \
    luanti \
    luanti-server \
    mesa-dri-gallium \
    mesa-gl \
    python3 \
    xvfb-run

COPY oni_cadia_game /usr/share/luanti/games/oni_cadia_game
COPY oni_cadia_api.py /usr/local/bin/oni_cadia_api.py
COPY oni_cadia_player_client.py /usr/local/bin/oni_cadia_player_client.py

EXPOSE 30000/udp
EXPOSE 30800/tcp

CMD ["minetestserver", "--config", "/var/lib/minetest/.minetest/minetest.conf", "--world", "/var/lib/minetest/.minetest/worlds/oni-cadia", "--gameid", "oni_cadia_game"]
